Ran a quick sanity check to ensure the tshock init script is available, and set up init install/uninstall code. Fixes issue #1.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -25,10 +25,17 @@ ME=$(whoami)
 
 # Original Arguments
 ARGS=$@
+STARTINGPATH=$(pwd)
 
 if [ "$(whoami)" != 'root' ]; then
    echo "This script must be run as root. Use \"sudo\" to accomplish this." 1>&2
    exit 1
+fi
+
+## Check to ensure tshock init file is available
+if [ ! -e ./tshock ] then
+  echo "Cannot continue! The init script \"tshock\" is missing! Please copy this file to the same directory as this install script to continue."
+  exit 1
 fi
 
 ## Install dependencies and create users
@@ -70,7 +77,7 @@ do
 done
 
 
-# Write default server.conf to /etc/tshock
+## Write default server.conf to /etc/tshock
 if [ ! -s /etc/tshock/server.conf ]; then
 contents="maxplayers=8
 worldpath=${SOURCEDIR}/Terraria/Worlds/
@@ -85,6 +92,8 @@ echo "$contents" > /etc/tshock/server.conf
 
 echo "The password set for the server is: \"${PASSWORD}\". Remember to change it in ${SERVERCONFIG}!"
 
-# Write tshock init script to init.d, and run update-rc.d
+## Write tshock init script to init.d, and run update-rc.d
+mv tshock /etc/init.d/tshock
+update-rc.d shock defaults 21
 
 echo “Installation complete! You can start your server now by typing \”sudo service tshock start\”.” 
